name: client-tests-workflow

on:
  pull_request

  jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
    # sert à récupérer le code du repo sur lequel le workflow est lancé
        uses: actions/checkout@v2
      - name: Goto client and run tests
        run: cd client && npm i && npm test